import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';

import { Sidebar } from '@/components/organisms/Sidebar';
import { Header } from '@/components/organisms/Header';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen w-full relative overflow-hidden`}
      >
      <div className="flex flex-col min-h-screen">
        <Header />

        <div className="flex flex-1 overflow-hidden">
          <Sidebar />

          <main className="flex-1 overflow-auto">
            <div className="container mx-auto px-6 py-6 space-y-6 bg-neutral-950">
              <NextIntlClientProvider>{children}</NextIntlClientProvider>
            </div>
          </main>
        </div>
      </div>
      </body>
    </html>
  );
}
